import { Property, PropertyType, PropertyStatus } from '@/types/property'
import { Booking, BookingStatus, PaymentStatus } from '@/types/booking'
import { Review } from '@/types/review'
import { Edition } from '@/types/edition'

// Mock property images - using placeholder services
const getImageUrl = (id: number, width = 800, height = 600) => 
  `https://picsum.photos/seed/property${id}/${width}/${height}`

// Generate mock properties
export const mockProperties: Property[] = [
  {
    id: '1',
    titleEn: 'Luxury Villa with Sea View in Mykonos',
    titleGr: 'Πολυτελής Βίλα με Θέα στη Θάλασσα στη Μύκονο',
    descriptionEn: 'Stunning luxury villa with panoramic sea views, private pool, and modern amenities. Perfect for a memorable Greek island vacation.',
    descriptionGr: 'Εντυπωσιακή πολυτελής βίλα με πανοραμική θέα στη θάλασσα, ιδιωτική πισίνα και σύγχρονα αmenities. Ιδανική για μια αξέχαστη διακοπή σε ελληνικό νησί.',
    type: 'LUXURY' as PropertyType,
    status: 'ACTIVE' as PropertyStatus,
    address: 'Paradise Beach Road 15',
    city: 'Mykonos',
    country: 'Greece',
    postalCode: '84600',
    latitude: 37.4467,
    longitude: 25.3289,
    maxGuests: 8,
    bedrooms: 4,
    bathrooms: 3,
    area: 250,
    basePrice: 450,
    currency: 'EUR',
    cleaningFee: 150,
    serviceFee: 45,
    serviceFeePercentage: 10,
    taxRate: 13,
    taxes: 58.5,
    minStay: 3,
    maxStay: 30,
    cancellationPolicy: 'MODERATE',
    hasDynamicRooms: false,
    averageCleanlinessRating: 4.9,
    lastCleaningDate: '2024-01-15',
    images: [
      getImageUrl(1, 1200, 800),
      getImageUrl(11, 1200, 800),
      getImageUrl(12, 1200, 800),
      getImageUrl(13, 1200, 800),
      getImageUrl(14, 1200, 800),
    ],
    videos: [],
    owner: {
      id: 'owner1',
      name: 'Maria Papadopoulos',
      avatar: 'https://i.pravatar.cc/150?img=5',
    },
    amenities: [
      {
        id: 'amenity1',
        propertyId: '1',
        amenityId: 'wifi',
        amenity: {
          id: 'wifi',
          nameEn: 'WiFi',
          nameGr: 'WiFi',
          icon: 'wifi',
          category: 'ESSENTIALS',
        },
      },
      {
        id: 'amenity2',
        propertyId: '1',
        amenityId: 'pool',
        amenity: {
          id: 'pool',
          nameEn: 'Swimming Pool',
          nameGr: 'Πισίνα',
          icon: 'pool',
          category: 'OUTDOOR',
        },
      },
      {
        id: 'amenity3',
        propertyId: '1',
        amenityId: 'beach',
        amenity: {
          id: 'beach',
          nameEn: 'Beach Access',
          nameGr: 'Πρόσβαση στην Παραλία',
          icon: 'beach',
          category: 'OUTDOOR',
        },
      },
      {
        id: 'amenity4',
        propertyId: '1',
        amenityId: 'kitchen',
        amenity: {
          id: 'kitchen',
          nameEn: 'Fully Equipped Kitchen',
          nameGr: 'Πλήρως Εξοπλισμένη Κουζίνα',
          icon: 'kitchen',
          category: 'KITCHEN',
        },
      },
      {
        id: 'amenity5',
        propertyId: '1',
        amenityId: 'parking',
        amenity: {
          id: 'parking',
          nameEn: 'Free Parking',
          nameGr: 'Δωρεάν Στάθμευση',
          icon: 'parking',
          category: 'PARKING',
        },
      },
    ],
    averageRating: 4.9,
    reviewCount: 47,
    createdAt: '2023-12-01T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    titleEn: 'Modern Apartment in Athens Center',
    titleGr: 'Σύγχρονο Διαμέρισμα στο Κέντρο της Αθήνας',
    descriptionEn: 'Beautiful modern apartment in the heart of Athens, walking distance to Acropolis and Plaka. Fully renovated with all modern conveniences.',
    descriptionGr: 'Όμορφο σύγχρονο διαμέρισμα στην καρδιά της Αθήνας, σε κοντινή απόσταση από την Ακρόπολη και την Πλάκα. Πλήρως ανακαινισμένο με όλες τις σύγχρονες ανέσεις.',
    type: 'APARTMENT' as PropertyType,
    status: 'ACTIVE' as PropertyStatus,
    address: 'Ermou Street 45',
    city: 'Athens',
    country: 'Greece',
    postalCode: '10563',
    latitude: 37.9755,
    longitude: 23.7348,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    area: 85,
    basePrice: 120,
    currency: 'EUR',
    cleaningFee: 50,
    serviceFee: 12,
    serviceFeePercentage: 10,
    taxRate: 13,
    taxes: 15.6,
    minStay: 2,
    maxStay: 90,
    cancellationPolicy: 'FLEXIBLE',
    hasDynamicRooms: false,
    averageCleanlinessRating: 4.7,
    lastCleaningDate: '2024-01-14',
    images: [
      getImageUrl(2, 1200, 800),
      getImageUrl(21, 1200, 800),
      getImageUrl(22, 1200, 800),
      getImageUrl(23, 1200, 800),
    ],
    videos: [],
    owner: {
      id: 'owner2',
      name: 'Dimitris Kostas',
      avatar: 'https://i.pravatar.cc/150?img=12',
    },
    amenities: [
      {
        id: 'amenity6',
        propertyId: '2',
        amenityId: 'wifi',
        amenity: {
          id: 'wifi',
          nameEn: 'WiFi',
          nameGr: 'WiFi',
          icon: 'wifi',
          category: 'ESSENTIALS',
        },
      },
      {
        id: 'amenity7',
        propertyId: '2',
        amenityId: 'kitchen',
        amenity: {
          id: 'kitchen',
          nameEn: 'Fully Equipped Kitchen',
          nameGr: 'Πλήρως Εξοπλισμένη Κουζίνα',
          icon: 'kitchen',
          category: 'KITCHEN',
        },
      },
      {
        id: 'amenity8',
        propertyId: '2',
        amenityId: 'ac',
        amenity: {
          id: 'ac',
          nameEn: 'Air Conditioning',
          nameGr: 'Κλιματισμός',
          icon: 'ac',
          category: 'CLIMATE',
        },
      },
    ],
    averageRating: 4.7,
    reviewCount: 32,
    createdAt: '2023-11-15T10:00:00Z',
    updatedAt: '2024-01-14T10:00:00Z',
  },
  {
    id: '3',
    titleEn: 'Seaside Studio in Santorini',
    titleGr: 'Στούντιο Δίπλα στη Θάλασσα στη Σαντορίνη',
    descriptionEn: 'Charming studio apartment with breathtaking caldera views. Perfect for couples seeking a romantic getaway.',
    descriptionGr: 'Γοητευτικό στούντιο με εκπληκτική θέα στον καλντέρα. Ιδανικό για ζευγάρια που αναζητούν μια ρομαντική διαφυγή.',
    type: 'APARTMENT' as PropertyType,
    status: 'ACTIVE' as PropertyStatus,
    address: 'Oia Village, Main Street 8',
    city: 'Santorini',
    country: 'Greece',
    postalCode: '84702',
    latitude: 36.4619,
    longitude: 25.3753,
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    area: 35,
    basePrice: 180,
    currency: 'EUR',
    cleaningFee: 40,
    serviceFee: 18,
    serviceFeePercentage: 10,
    taxRate: 13,
    taxes: 23.4,
    minStay: 2,
    maxStay: 14,
    cancellationPolicy: 'STRICT',
    hasDynamicRooms: false,
    averageCleanlinessRating: 4.8,
    lastCleaningDate: '2024-01-13',
    images: [
      getImageUrl(3, 1200, 800),
      getImageUrl(31, 1200, 800),
      getImageUrl(32, 1200, 800),
      getImageUrl(33, 1200, 800),
    ],
    videos: [],
    owner: {
      id: 'owner3',
      name: 'Elena Nikolaou',
      avatar: 'https://i.pravatar.cc/150?img=9',
    },
    amenities: [
      {
        id: 'amenity9',
        propertyId: '3',
        amenityId: 'wifi',
        amenity: {
          id: 'wifi',
          nameEn: 'WiFi',
          nameGr: 'WiFi',
          icon: 'wifi',
          category: 'ESSENTIALS',
        },
      },
      {
        id: 'amenity10',
        propertyId: '3',
        amenityId: 'balcony',
        amenity: {
          id: 'balcony',
          nameEn: 'Balcony with View',
          nameGr: 'Μπαλκόνι με Θέα',
          icon: 'balcony',
          category: 'OUTDOOR',
        },
      },
    ],
    averageRating: 4.8,
    reviewCount: 89,
    createdAt: '2023-10-20T10:00:00Z',
    updatedAt: '2024-01-13T10:00:00Z',
  },
  {
    id: '4',
    titleEn: 'Traditional House in Crete',
    titleGr: 'Παραδοσιακό Σπίτι στην Κρήτη',
    descriptionEn: 'Authentic Cretan stone house with traditional architecture, large garden, and mountain views. Experience true Greek hospitality.',
    descriptionGr: 'Αυθεντικό κρητικό πέτρινο σπίτι με παραδοσιακή αρχιτεκτονική, μεγάλο κήπο και θέα στα βουνά. Ζήστε την αληθινή ελληνική φιλοξενία.',
    type: 'HOUSE' as PropertyType,
    status: 'ACTIVE' as PropertyStatus,
    address: 'Chania Old Town, Venetian Harbor 12',
    city: 'Chania',
    country: 'Greece',
    postalCode: '73100',
    latitude: 35.5153,
    longitude: 24.0183,
    maxGuests: 6,
    bedrooms: 3,
    bathrooms: 2,
    area: 180,
    basePrice: 200,
    currency: 'EUR',
    cleaningFee: 80,
    serviceFee: 20,
    serviceFeePercentage: 10,
    taxRate: 13,
    taxes: 26,
    minStay: 4,
    maxStay: 60,
    cancellationPolicy: 'MODERATE',
    hasDynamicRooms: false,
    averageCleanlinessRating: 4.6,
    lastCleaningDate: '2024-01-12',
    images: [
      getImageUrl(4, 1200, 800),
      getImageUrl(41, 1200, 800),
      getImageUrl(42, 1200, 800),
      getImageUrl(43, 1200, 800),
      getImageUrl(44, 1200, 800),
      getImageUrl(45, 1200, 800),
    ],
    videos: [],
    owner: {
      id: 'owner4',
      name: 'Yannis Manolis',
      avatar: 'https://i.pravatar.cc/150?img=15',
    },
    amenities: [
      {
        id: 'amenity11',
        propertyId: '4',
        amenityId: 'wifi',
        amenity: {
          id: 'wifi',
          nameEn: 'WiFi',
          nameGr: 'WiFi',
          icon: 'wifi',
          category: 'ESSENTIALS',
        },
      },
      {
        id: 'amenity12',
        propertyId: '4',
        amenityId: 'garden',
        amenity: {
          id: 'garden',
          nameEn: 'Garden',
          nameGr: 'Κήπος',
          icon: 'garden',
          category: 'OUTDOOR',
        },
      },
      {
        id: 'amenity13',
        propertyId: '4',
        amenityId: 'kitchen',
        amenity: {
          id: 'kitchen',
          nameEn: 'Fully Equipped Kitchen',
          nameGr: 'Πλήρως Εξοπλισμένη Κουζίνα',
          icon: 'kitchen',
          category: 'KITCHEN',
        },
      },
    ],
    averageRating: 4.6,
    reviewCount: 24,
    createdAt: '2023-09-10T10:00:00Z',
    updatedAt: '2024-01-12T10:00:00Z',
  },
  {
    id: '5',
    titleEn: 'Beachfront Apartment in Paros',
    titleGr: 'Διαμέρισμα Δίπλα στη Θάλασσα στην Πάρο',
    descriptionEn: 'Spacious beachfront apartment with direct access to golden sand beach. Modern amenities and stunning sunset views.',
    descriptionGr: 'Ευρύχωρο διαμέρισμα δίπλα στη θάλασσα με άμεση πρόσβαση σε χρυσή παραλία. Σύγχρονα amenities και εκπληκτική θέα στο ηλιοβασίλεμα.',
    type: 'APARTMENT' as PropertyType,
    status: 'ACTIVE' as PropertyStatus,
    address: 'Parikia Beach Road 22',
    city: 'Paros',
    country: 'Greece',
    postalCode: '84400',
    latitude: 37.0853,
    longitude: 25.1483,
    maxGuests: 5,
    bedrooms: 2,
    bathrooms: 2,
    area: 95,
    basePrice: 150,
    currency: 'EUR',
    cleaningFee: 60,
    serviceFee: 15,
    serviceFeePercentage: 10,
    taxRate: 13,
    taxes: 19.5,
    minStay: 3,
    maxStay: 30,
    cancellationPolicy: 'FLEXIBLE',
    hasDynamicRooms: false,
    averageCleanlinessRating: 4.8,
    lastCleaningDate: '2024-01-11',
    images: [
      getImageUrl(5, 1200, 800),
      getImageUrl(51, 1200, 800),
      getImageUrl(52, 1200, 800),
      getImageUrl(53, 1200, 800),
    ],
    videos: [],
    owner: {
      id: 'owner5',
      name: 'Sophia Petrou',
      avatar: 'https://i.pravatar.cc/150?img=20',
    },
    amenities: [
      {
        id: 'amenity14',
        propertyId: '5',
        amenityId: 'wifi',
        amenity: {
          id: 'wifi',
          nameEn: 'WiFi',
          nameGr: 'WiFi',
          icon: 'wifi',
          category: 'ESSENTIALS',
        },
      },
      {
        id: 'amenity15',
        propertyId: '5',
        amenityId: 'beach',
        amenity: {
          id: 'beach',
          nameEn: 'Beach Access',
          nameGr: 'Πρόσβαση στην Παραλία',
          icon: 'beach',
          category: 'OUTDOOR',
        },
      },
      {
        id: 'amenity16',
        propertyId: '5',
        amenityId: 'parking',
        amenity: {
          id: 'parking',
          nameEn: 'Free Parking',
          nameGr: 'Δωρεάν Στάθμευση',
          icon: 'parking',
          category: 'PARKING',
        },
      },
    ],
    averageRating: 4.8,
    reviewCount: 56,
    createdAt: '2023-11-01T10:00:00Z',
    updatedAt: '2024-01-11T10:00:00Z',
  },
  {
    id: '6',
    titleEn: 'Cozy Studio in Thessaloniki',
    titleGr: 'Ζεστό Στούντιο στη Θεσσαλονίκη',
    descriptionEn: 'Comfortable studio apartment in the heart of Thessaloniki, close to restaurants, cafes, and cultural sites.',
    descriptionGr: 'Άνετο στούντιο στην καρδιά της Θεσσαλονίκης, κοντά σε εστιατόρια, καφέ και πολιτιστικούς χώρους.',
    type: 'APARTMENT' as PropertyType,
    status: 'ACTIVE' as PropertyStatus,
    address: 'Aristotelous Square 7',
    city: 'Thessaloniki',
    country: 'Greece',
    postalCode: '54625',
    latitude: 40.6401,
    longitude: 22.9444,
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    area: 30,
    basePrice: 80,
    currency: 'EUR',
    cleaningFee: 30,
    serviceFee: 8,
    serviceFeePercentage: 10,
    taxRate: 13,
    taxes: 10.4,
    minStay: 1,
    maxStay: 180,
    cancellationPolicy: 'FLEXIBLE',
    hasDynamicRooms: false,
    averageCleanlinessRating: 4.5,
    lastCleaningDate: '2024-01-10',
    images: [
      getImageUrl(6, 1200, 800),
      getImageUrl(61, 1200, 800),
      getImageUrl(62, 1200, 800),
    ],
    videos: [],
    owner: {
      id: 'owner6',
      name: 'Nikos Georgiou',
      avatar: 'https://i.pravatar.cc/150?img=33',
    },
    amenities: [
      {
        id: 'amenity17',
        propertyId: '6',
        amenityId: 'wifi',
        amenity: {
          id: 'wifi',
          nameEn: 'WiFi',
          nameGr: 'WiFi',
          icon: 'wifi',
          category: 'ESSENTIALS',
        },
      },
      {
        id: 'amenity18',
        propertyId: '6',
        amenityId: 'ac',
        amenity: {
          id: 'ac',
          nameEn: 'Air Conditioning',
          nameGr: 'Κλιματισμός',
          icon: 'ac',
          category: 'CLIMATE',
        },
      },
    ],
    averageRating: 4.5,
    reviewCount: 18,
    createdAt: '2023-12-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: '7',
    titleEn: 'Luxury Penthouse in Rhodes',
    titleGr: 'Πολυτελές Πεντάκτινο στη Ρόδο',
    descriptionEn: 'Stunning penthouse with panoramic views of the Aegean Sea. Rooftop terrace, modern design, and premium amenities.',
    descriptionGr: 'Εντυπωσιακό πεντάκτινο με πανοραμική θέα στο Αιγαίο. Τεράστια ταράτσα, σύγχρονος σχεδιασμός και premium amenities.',
    type: 'LUXURY' as PropertyType,
    status: 'ACTIVE' as PropertyStatus,
    address: 'Old Town, Knights Street 5',
    city: 'Rhodes',
    country: 'Greece',
    postalCode: '85100',
    latitude: 36.4412,
    longitude: 28.2225,
    maxGuests: 6,
    bedrooms: 3,
    bathrooms: 2,
    area: 200,
    basePrice: 350,
    currency: 'EUR',
    cleaningFee: 120,
    serviceFee: 35,
    serviceFeePercentage: 10,
    taxRate: 13,
    taxes: 45.5,
    minStay: 4,
    maxStay: 30,
    cancellationPolicy: 'MODERATE',
    hasDynamicRooms: false,
    averageCleanlinessRating: 4.9,
    lastCleaningDate: '2024-01-09',
    images: [
      getImageUrl(7, 1200, 800),
      getImageUrl(71, 1200, 800),
      getImageUrl(72, 1200, 800),
      getImageUrl(73, 1200, 800),
      getImageUrl(74, 1200, 800),
    ],
    videos: [],
    owner: {
      id: 'owner7',
      name: 'Alexandra Stavrou',
      avatar: 'https://i.pravatar.cc/150?img=47',
    },
    amenities: [
      {
        id: 'amenity19',
        propertyId: '7',
        amenityId: 'wifi',
        amenity: {
          id: 'wifi',
          nameEn: 'WiFi',
          nameGr: 'WiFi',
          icon: 'wifi',
          category: 'ESSENTIALS',
        },
      },
      {
        id: 'amenity20',
        propertyId: '7',
        amenityId: 'terrace',
        amenity: {
          id: 'terrace',
          nameEn: 'Rooftop Terrace',
          nameGr: 'Ταράτσα',
          icon: 'terrace',
          category: 'OUTDOOR',
        },
      },
      {
        id: 'amenity21',
        propertyId: '7',
        amenityId: 'kitchen',
        amenity: {
          id: 'kitchen',
          nameEn: 'Fully Equipped Kitchen',
          nameGr: 'Πλήρως Εξοπλισμένη Κουζίνα',
          icon: 'kitchen',
          category: 'KITCHEN',
        },
      },
    ],
    averageRating: 4.9,
    reviewCount: 41,
    createdAt: '2023-10-05T10:00:00Z',
    updatedAt: '2024-01-09T10:00:00Z',
  },
  {
    id: '8',
    titleEn: 'Mountain Retreat in Zagori',
    titleGr: 'Ορεινό Καταφύγιο στα Ζαγόρια',
    descriptionEn: 'Peaceful mountain house surrounded by nature. Perfect for hiking enthusiasts and those seeking tranquility.',
    descriptionGr: 'Ήσυχο ορεινό σπίτι περιτριγυρισμένο από τη φύση. Ιδανικό για τους λάτρεις του hiking και όσους αναζητούν ησυχία.',
    type: 'HOUSE' as PropertyType,
    status: 'ACTIVE' as PropertyStatus,
    address: 'Zagori Village, Mountain Road 3',
    city: 'Zagori',
    country: 'Greece',
    postalCode: '44007',
    latitude: 39.8961,
    longitude: 20.7303,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    area: 120,
    basePrice: 100,
    currency: 'EUR',
    cleaningFee: 50,
    serviceFee: 10,
    serviceFeePercentage: 10,
    taxRate: 13,
    taxes: 13,
    minStay: 2,
    maxStay: 90,
    cancellationPolicy: 'FLEXIBLE',
    hasDynamicRooms: false,
    averageCleanlinessRating: 4.7,
    lastCleaningDate: '2024-01-08',
    images: [
      getImageUrl(8, 1200, 800),
      getImageUrl(81, 1200, 800),
      getImageUrl(82, 1200, 800),
      getImageUrl(83, 1200, 800),
    ],
    videos: [],
    owner: {
      id: 'owner8',
      name: 'Petros Dimitriou',
      avatar: 'https://i.pravatar.cc/150?img=51',
    },
    amenities: [
      {
        id: 'amenity22',
        propertyId: '8',
        amenityId: 'wifi',
        amenity: {
          id: 'wifi',
          nameEn: 'WiFi',
          nameGr: 'WiFi',
          icon: 'wifi',
          category: 'ESSENTIALS',
        },
      },
      {
        id: 'amenity23',
        propertyId: '8',
        amenityId: 'fireplace',
        amenity: {
          id: 'fireplace',
          nameEn: 'Fireplace',
          nameGr: 'Τζάκι',
          icon: 'fireplace',
          category: 'CLIMATE',
        },
      },
      {
        id: 'amenity24',
        propertyId: '8',
        amenityId: 'garden',
        amenity: {
          id: 'garden',
          nameEn: 'Garden',
          nameGr: 'Κήπος',
          icon: 'garden',
          category: 'OUTDOOR',
        },
      },
    ],
    averageRating: 4.7,
    reviewCount: 15,
    createdAt: '2023-11-20T10:00:00Z',
    updatedAt: '2024-01-08T10:00:00Z',
  },
  {
    id: '9',
    titleEn: 'Beach House in Naxos',
    titleGr: 'Σπίτι στην Παραλία στη Νάξο',
    descriptionEn: 'Beautiful beach house with direct beach access. Spacious and perfect for families. Stunning sunset views every evening.',
    descriptionGr: 'Όμορφο σπίτι στην παραλία με άμεση πρόσβαση στη θάλασσα. Ευρύχωρο και ιδανικό για οικογένειες. Εκπληκτική θέα στο ηλιοβασίλεμα κάθε βράδυ.',
    type: 'HOUSE' as PropertyType,
    status: 'ACTIVE' as PropertyStatus,
    address: 'Plaka Beach, Coastal Road 18',
    city: 'Naxos',
    country: 'Greece',
    postalCode: '84300',
    latitude: 37.1036,
    longitude: 25.3767,
    maxGuests: 7,
    bedrooms: 3,
    bathrooms: 2,
    area: 160,
    basePrice: 220,
    currency: 'EUR',
    cleaningFee: 90,
    serviceFee: 22,
    serviceFeePercentage: 10,
    taxRate: 13,
    taxes: 28.6,
    minStay: 5,
    maxStay: 30,
    cancellationPolicy: 'MODERATE',
    hasDynamicRooms: false,
    averageCleanlinessRating: 4.8,
    lastCleaningDate: '2024-01-07',
    images: [
      getImageUrl(9, 1200, 800),
      getImageUrl(91, 1200, 800),
      getImageUrl(92, 1200, 800),
      getImageUrl(93, 1200, 800),
      getImageUrl(94, 1200, 800),
    ],
    videos: [],
    owner: {
      id: 'owner9',
      name: 'Katerina Vlahou',
      avatar: 'https://i.pravatar.cc/150?img=25',
    },
    amenities: [
      {
        id: 'amenity25',
        propertyId: '9',
        amenityId: 'wifi',
        amenity: {
          id: 'wifi',
          nameEn: 'WiFi',
          nameGr: 'WiFi',
          icon: 'wifi',
          category: 'ESSENTIALS',
        },
      },
      {
        id: 'amenity26',
        propertyId: '9',
        amenityId: 'beach',
        amenity: {
          id: 'beach',
          nameEn: 'Beach Access',
          nameGr: 'Πρόσβαση στην Παραλία',
          icon: 'beach',
          category: 'OUTDOOR',
        },
      },
      {
        id: 'amenity27',
        propertyId: '9',
        amenityId: 'kitchen',
        amenity: {
          id: 'kitchen',
          nameEn: 'Fully Equipped Kitchen',
          nameGr: 'Πλήρως Εξοπλισμένη Κουζίνα',
          icon: 'kitchen',
          category: 'KITCHEN',
        },
      },
      {
        id: 'amenity28',
        propertyId: '9',
        amenityId: 'parking',
        amenity: {
          id: 'parking',
          nameEn: 'Free Parking',
          nameGr: 'Δωρεάν Στάθμευση',
          icon: 'parking',
          category: 'PARKING',
        },
      },
    ],
    averageRating: 4.8,
    reviewCount: 38,
    createdAt: '2023-09-25T10:00:00Z',
    updatedAt: '2024-01-07T10:00:00Z',
  },
  {
    id: '10',
    titleEn: 'City Loft in Patras',
    titleGr: 'Loft στο Κέντρο της Πάτρας',
    descriptionEn: 'Modern industrial-style loft in the city center. High ceilings, exposed brick, and contemporary design.',
    descriptionGr: 'Σύγχρονο loft βιομηχανικού στυλ στο κέντρο της πόλης. Ψηλές οροφές, εκτεθειμένο τούβλο και σύγχρονος σχεδιασμός.',
    type: 'APARTMENT' as PropertyType,
    status: 'ACTIVE' as PropertyStatus,
    address: 'Georgiou Square 14',
    city: 'Patras',
    country: 'Greece',
    postalCode: '26221',
    latitude: 38.2466,
    longitude: 21.7346,
    maxGuests: 3,
    bedrooms: 1,
    bathrooms: 1,
    area: 55,
    basePrice: 90,
    currency: 'EUR',
    cleaningFee: 35,
    serviceFee: 9,
    serviceFeePercentage: 10,
    taxRate: 13,
    taxes: 11.7,
    minStay: 1,
    maxStay: 180,
    cancellationPolicy: 'FLEXIBLE',
    hasDynamicRooms: false,
    averageCleanlinessRating: 4.6,
    lastCleaningDate: '2024-01-06',
    images: [
      getImageUrl(10, 1200, 800),
      getImageUrl(101, 1200, 800),
      getImageUrl(102, 1200, 800),
      getImageUrl(103, 1200, 800),
    ],
    videos: [],
    owner: {
      id: 'owner10',
      name: 'Andreas Papadakis',
      avatar: 'https://i.pravatar.cc/150?img=29',
    },
    amenities: [
      {
        id: 'amenity29',
        propertyId: '10',
        amenityId: 'wifi',
        amenity: {
          id: 'wifi',
          nameEn: 'WiFi',
          nameGr: 'WiFi',
          icon: 'wifi',
          category: 'ESSENTIALS',
        },
      },
      {
        id: 'amenity30',
        propertyId: '10',
        amenityId: 'ac',
        amenity: {
          id: 'ac',
          nameEn: 'Air Conditioning',
          nameGr: 'Κλιματισμός',
          icon: 'ac',
          category: 'CLIMATE',
        },
      },
    ],
    averageRating: 4.6,
    reviewCount: 12,
    createdAt: '2023-12-05T10:00:00Z',
    updatedAt: '2024-01-06T10:00:00Z',
  },
  {
    id: '11',
    titleEn: 'Villa with Infinity Pool in Corfu',
    titleGr: 'Βίλα με Infinity Pool στην Κέρκυρα',
    descriptionEn: 'Luxurious villa with infinity pool overlooking the Ionian Sea. Modern architecture meets traditional Greek charm.',
    descriptionGr: 'Πολυτελής βίλα με infinity pool με θέα στο Ιόνιο. Σύγχρονη αρχιτεκτονική συναντά παραδοσιακή ελληνική γοητεία.',
    type: 'LUXURY' as PropertyType,
    status: 'ACTIVE' as PropertyStatus,
    address: 'Paleokastritsa Bay, Villa Road 25',
    city: 'Corfu',
    country: 'Greece',
    postalCode: '49083',
    latitude: 39.6753,
    longitude: 19.7217,
    maxGuests: 10,
    bedrooms: 5,
    bathrooms: 4,
    area: 400,
    basePrice: 600,
    currency: 'EUR',
    cleaningFee: 200,
    serviceFee: 60,
    serviceFeePercentage: 10,
    taxRate: 13,
    taxes: 78,
    minStay: 7,
    maxStay: 30,
    cancellationPolicy: 'STRICT',
    hasDynamicRooms: false,
    averageCleanlinessRating: 5.0,
    lastCleaningDate: '2024-01-16',
    images: [
      getImageUrl(11, 1200, 800),
      getImageUrl(111, 1200, 800),
      getImageUrl(112, 1200, 800),
      getImageUrl(113, 1200, 800),
      getImageUrl(114, 1200, 800),
      getImageUrl(115, 1200, 800),
    ],
    videos: [],
    owner: {
      id: 'owner11',
      name: 'Christos Makris',
      avatar: 'https://i.pravatar.cc/150?img=36',
    },
    amenities: [
      {
        id: 'amenity31',
        propertyId: '11',
        amenityId: 'wifi',
        amenity: {
          id: 'wifi',
          nameEn: 'WiFi',
          nameGr: 'WiFi',
          icon: 'wifi',
          category: 'ESSENTIALS',
        },
      },
      {
        id: 'amenity32',
        propertyId: '11',
        amenityId: 'pool',
        amenity: {
          id: 'pool',
          nameEn: 'Infinity Pool',
          nameGr: 'Infinity Pool',
          icon: 'pool',
          category: 'OUTDOOR',
        },
      },
      {
        id: 'amenity33',
        propertyId: '11',
        amenityId: 'beach',
        amenity: {
          id: 'beach',
          nameEn: 'Beach Access',
          nameGr: 'Πρόσβαση στην Παραλία',
          icon: 'beach',
          category: 'OUTDOOR',
        },
      },
      {
        id: 'amenity34',
        propertyId: '11',
        amenityId: 'kitchen',
        amenity: {
          id: 'kitchen',
          nameEn: 'Fully Equipped Kitchen',
          nameGr: 'Πλήρως Εξοπλισμένη Κουζίνα',
          icon: 'kitchen',
          category: 'KITCHEN',
        },
      },
      {
        id: 'amenity35',
        propertyId: '11',
        amenityId: 'parking',
        amenity: {
          id: 'parking',
          nameEn: 'Free Parking',
          nameGr: 'Δωρεάν Στάθμευση',
          icon: 'parking',
          category: 'PARKING',
        },
      },
    ],
    averageRating: 5.0,
    reviewCount: 62,
    createdAt: '2023-08-15T10:00:00Z',
    updatedAt: '2024-01-16T10:00:00Z',
  },
  {
    id: '12',
    titleEn: 'Cozy Apartment in Heraklion',
    titleGr: 'Ζεστό Διαμέρισμα στο Ηράκλειο',
    descriptionEn: 'Comfortable apartment in the heart of Heraklion, close to the archaeological museum and Venetian port.',
    descriptionGr: 'Άνετο διαμέρισμα στην καρδιά του Ηρακλείου, κοντά στο αρχαιολογικό μουσείο και το βενετσιάνικο λιμάνι.',
    type: 'APARTMENT' as PropertyType,
    status: 'ACTIVE' as PropertyStatus,
    address: 'Dedalou Street 28',
    city: 'Heraklion',
    country: 'Greece',
    postalCode: '71202',
    latitude: 35.3080,
    longitude: 25.0775,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    area: 70,
    basePrice: 110,
    currency: 'EUR',
    cleaningFee: 45,
    serviceFee: 11,
    serviceFeePercentage: 10,
    taxRate: 13,
    taxes: 14.3,
    minStay: 2,
    maxStay: 90,
    cancellationPolicy: 'FLEXIBLE',
    hasDynamicRooms: false,
    averageCleanlinessRating: 4.7,
    lastCleaningDate: '2024-01-05',
    images: [
      getImageUrl(12, 1200, 800),
      getImageUrl(121, 1200, 800),
      getImageUrl(122, 1200, 800),
      getImageUrl(123, 1200, 800),
    ],
    videos: [],
    owner: {
      id: 'owner12',
      name: 'Ioanna Kiriakou',
      avatar: 'https://i.pravatar.cc/150?img=42',
    },
    amenities: [
      {
        id: 'amenity36',
        propertyId: '12',
        amenityId: 'wifi',
        amenity: {
          id: 'wifi',
          nameEn: 'WiFi',
          nameGr: 'WiFi',
          icon: 'wifi',
          category: 'ESSENTIALS',
        },
      },
      {
        id: 'amenity37',
        propertyId: '12',
        amenityId: 'kitchen',
        amenity: {
          id: 'kitchen',
          nameEn: 'Fully Equipped Kitchen',
          nameGr: 'Πλήρως Εξοπλισμένη Κουζίνα',
          icon: 'kitchen',
          category: 'KITCHEN',
        },
      },
    ],
    averageRating: 4.7,
    reviewCount: 28,
    createdAt: '2023-11-12T10:00:00Z',
    updatedAt: '2024-01-05T10:00:00Z',
  },
]

// Generate more properties to reach 30+
const generateMoreProperties = (): Property[] => {
  const cities = [
    { name: 'Kavala', country: 'Greece', lat: 40.9393, lng: 24.4067, postal: '65302' },
    { name: 'Volos', country: 'Greece', lat: 39.3610, lng: 22.9427, postal: '38200' },
    { name: 'Ioannina', country: 'Greece', lat: 39.6650, lng: 20.8537, postal: '45221' },
    { name: 'Kalamata', country: 'Greece', lat: 37.0374, lng: 22.1106, postal: '24100' },
    { name: 'Larissa', country: 'Greece', lat: 39.6390, lng: 22.4191, postal: '41335' },
    { name: 'Zakynthos', country: 'Greece', lat: 37.7833, lng: 20.9000, postal: '29100' },
    { name: 'Kefalonia', country: 'Greece', lat: 38.1754, lng: 20.5692, postal: '28100' },
    { name: 'Milos', country: 'Greece', lat: 36.7215, lng: 24.4253, postal: '84800' },
    { name: 'Ios', country: 'Greece', lat: 36.7215, lng: 25.2833, postal: '84001' },
    { name: 'Skiathos', country: 'Greece', lat: 39.1623, lng: 23.4903, postal: '37002' },
  ]

  const types: PropertyType[] = ['APARTMENT', 'HOUSE', 'LUXURY', 'APARTMENT', 'HOUSE']
  const titlesEn = [
    'Modern Apartment',
    'Cozy House',
    'Luxury Villa',
    'Beachfront Property',
    'City Center Apartment',
    'Mountain Retreat',
    'Seaside Studio',
    'Traditional Home',
    'Contemporary Loft',
    'Garden Villa',
  ]
  const titlesGr = [
    'Σύγχρονο Διαμέρισμα',
    'Ζεστό Σπίτι',
    'Πολυτελής Βίλα',
    'Ακίνητο Δίπλα στη Θάλασσα',
    'Διαμέρισμα στο Κέντρο',
    'Ορεινό Καταφύγιο',
    'Στούντιο Δίπλα στη Θάλασσα',
    'Παραδοσιακό Σπίτι',
    'Σύγχρονο Loft',
    'Βίλα με Κήπο',
  ]

  return cities.flatMap((city, cityIndex) => {
    return types.map((type, typeIndex) => {
      const id = 13 + cityIndex * types.length + typeIndex
      const titleIndex = (cityIndex + typeIndex) % titlesEn.length
      const basePrice = type === 'LUXURY' ? 400 + Math.random() * 300 : type === 'HOUSE' ? 150 + Math.random() * 150 : 80 + Math.random() * 100
      
      return {
        id: id.toString(),
        titleEn: `${titlesEn[titleIndex]} in ${city.name}`,
        titleGr: `${titlesGr[titleIndex]} στην ${city.name}`,
        descriptionEn: `Beautiful property in ${city.name}. Perfect for your stay.`,
        descriptionGr: `Όμορφο ακίνητο στην ${city.name}. Ιδανικό για τη διαμονή σας.`,
        type,
        status: 'ACTIVE' as PropertyStatus,
        address: `Main Street ${Math.floor(Math.random() * 100)}`,
        city: city.name,
        country: city.country,
        postalCode: city.postal,
        latitude: city.lat + (Math.random() - 0.5) * 0.1,
        longitude: city.lng + (Math.random() - 0.5) * 0.1,
        maxGuests: type === 'LUXURY' ? 8 : type === 'HOUSE' ? 6 : 4,
        bedrooms: type === 'LUXURY' ? 4 : type === 'HOUSE' ? 3 : 2,
        bathrooms: type === 'LUXURY' ? 3 : type === 'HOUSE' ? 2 : 1,
        area: type === 'LUXURY' ? 250 : type === 'HOUSE' ? 150 : 70,
        basePrice: Math.round(basePrice),
        currency: 'EUR',
        cleaningFee: Math.round(basePrice * 0.3),
        serviceFee: Math.round(basePrice * 0.1),
        serviceFeePercentage: 10,
        taxRate: 13,
        taxes: Math.round(basePrice * 0.13),
        minStay: type === 'LUXURY' ? 5 : 2,
        maxStay: 30,
        cancellationPolicy: type === 'LUXURY' ? 'STRICT' : 'MODERATE',
        hasDynamicRooms: false,
        averageCleanlinessRating: 4.5 + Math.random() * 0.5,
        lastCleaningDate: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        images: Array.from({ length: 4 }, (_, i) => getImageUrl(id * 10 + i, 1200, 800)),
        videos: [],
        owner: {
          id: `owner${id}`,
          name: `Owner ${id}`,
          avatar: `https://i.pravatar.cc/150?img=${id}`,
        },
        amenities: [
          {
            id: `amenity${id * 3}`,
            propertyId: id.toString(),
            amenityId: 'wifi',
            amenity: {
              id: 'wifi',
              nameEn: 'WiFi',
              nameGr: 'WiFi',
              icon: 'wifi',
              category: 'ESSENTIALS',
            },
          },
          ...(type === 'LUXURY' || type === 'HOUSE' ? [
            {
              id: `amenity${id * 3 + 1}`,
              propertyId: id.toString(),
              amenityId: 'kitchen',
              amenity: {
                id: 'kitchen',
                nameEn: 'Fully Equipped Kitchen',
                nameGr: 'Πλήρως Εξοπλισμένη Κουζίνα',
                icon: 'kitchen',
                category: 'KITCHEN',
              },
            },
          ] : []),
        ],
        averageRating: 4.5 + Math.random() * 0.5,
        reviewCount: Math.floor(Math.random() * 50) + 5,
        createdAt: new Date(Date.now() - Math.random() * 90 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date().toISOString(),
      } as Property
    })
  })
}

export const allMockProperties = [...mockProperties, ...generateMoreProperties()]

// Mock reviews
export const mockReviews: Review[] = [
  {
    id: 'review1',
    propertyId: '1',
    bookingId: 'booking1',
    guestId: 'guest1',
    rating: 5,
    cleanlinessRating: 5,
    accuracyRating: 5,
    communicationRating: 5,
    locationRating: 5,
    valueRating: 5,
    title: 'Absolutely Amazing!',
    comment: 'This villa exceeded all our expectations. The views are breathtaking and the host was incredibly helpful.',
    isPublic: true,
    guest: {
      id: 'guest1',
      name: 'John Smith',
      avatar: 'https://i.pravatar.cc/150?img=1',
    },
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'review2',
    propertyId: '1',
    bookingId: 'booking2',
    guestId: 'guest2',
    rating: 5,
    cleanlinessRating: 5,
    accuracyRating: 4,
    communicationRating: 5,
    locationRating: 5,
    valueRating: 5,
    title: 'Perfect Stay',
    comment: 'Beautiful property with everything we needed. Highly recommend!',
    isPublic: true,
    guest: {
      id: 'guest2',
      name: 'Sarah Johnson',
      avatar: 'https://i.pravatar.cc/150?img=2',
    },
    createdAt: '2024-01-08T10:00:00Z',
    updatedAt: '2024-01-08T10:00:00Z',
  },
  {
    id: 'review3',
    propertyId: '2',
    bookingId: 'booking3',
    guestId: 'guest3',
    rating: 4,
    cleanlinessRating: 4,
    accuracyRating: 4,
    communicationRating: 5,
    locationRating: 5,
    valueRating: 4,
    title: 'Great Location',
    comment: 'Perfect location in the heart of Athens. The apartment was clean and comfortable.',
    isPublic: true,
    guest: {
      id: 'guest3',
      name: 'Michael Brown',
      avatar: 'https://i.pravatar.cc/150?img=3',
    },
    createdAt: '2024-01-05T10:00:00Z',
    updatedAt: '2024-01-05T10:00:00Z',
  },
]

// Generate more reviews for all properties
export const generateMockReviews = (propertyId: string, count: number): Review[] => {
  const names = ['Alex', 'Maria', 'Nikos', 'Elena', 'Dimitris', 'Sophia', 'Petros', 'Katerina']
  const comments = [
    'Great stay, would definitely come back!',
    'Perfect location and very clean.',
    'The host was very responsive and helpful.',
    'Beautiful property with amazing views.',
    'Everything was exactly as described.',
    'Highly recommend this place!',
    'Wonderful experience, thank you!',
    'Clean, comfortable, and well-located.',
  ]

  return Array.from({ length: count }, (_, i) => ({
    id: `review-${propertyId}-${i}`,
    propertyId,
    bookingId: `booking-${propertyId}-${i}`,
    guestId: `guest-${propertyId}-${i}`,
    rating: 4 + Math.random(),
    cleanlinessRating: 4 + Math.random(),
    accuracyRating: 4 + Math.random(),
    communicationRating: 4 + Math.random(),
    locationRating: 4 + Math.random(),
    valueRating: 4 + Math.random(),
    title: ['Amazing!', 'Great Stay', 'Perfect', 'Wonderful', 'Excellent'][Math.floor(Math.random() * 5)],
    comment: comments[Math.floor(Math.random() * comments.length)],
    isPublic: true,
    guest: {
      id: `guest-${propertyId}-${i}`,
      name: names[Math.floor(Math.random() * names.length)],
      avatar: `https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 70)}`,
    },
    createdAt: new Date(Date.now() - Math.random() * 90 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  }))
}

// Mock bookings
export const mockBookings: Booking[] = [
  {
    id: 'booking1',
    propertyId: '1',
    guestId: 'guest1',
    status: 'CONFIRMED' as BookingStatus,
    paymentStatus: 'COMPLETED' as PaymentStatus,
    checkIn: '2024-02-01',
    checkOut: '2024-02-05',
    guests: 4,
    totalPrice: 1950,
    basePrice: 1800,
    cleaningFee: 150,
    serviceFee: 180,
    taxes: 234,
    currency: 'EUR',
    ownerRevenue: 1620,
    platformFee: 180,
    guestName: 'John Smith',
    guestEmail: 'john@example.com',
    guestPhone: '+30 123456789',
    specialRequests: 'Late check-in please',
    property: {
      id: '1',
      titleEn: 'Luxury Villa with Sea View in Mykonos',
      titleGr: 'Πολυτελής Βίλα με Θέα στη Θάλασσα στη Μύκονο',
      images: [getImageUrl(1, 400, 300)],
      address: 'Paradise Beach Road 15',
      city: 'Mykonos',
    },
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'booking2',
    propertyId: '2',
    guestId: 'guest2',
    status: 'CHECKED_IN' as BookingStatus,
    paymentStatus: 'COMPLETED' as PaymentStatus,
    checkIn: '2024-01-20',
    checkOut: '2024-01-25',
    guests: 2,
    totalPrice: 600,
    basePrice: 600,
    cleaningFee: 50,
    serviceFee: 60,
    taxes: 78,
    currency: 'EUR',
    ownerRevenue: 540,
    platformFee: 60,
    guestName: 'Sarah Johnson',
    guestEmail: 'sarah@example.com',
    property: {
      id: '2',
      titleEn: 'Modern Apartment in Athens Center',
      titleGr: 'Σύγχρονο Διαμέρισμα στο Κέντρο της Αθήνας',
      images: [getImageUrl(2, 400, 300)],
      address: 'Ermou Street 45',
      city: 'Athens',
    },
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-20T10:00:00Z',
  },
]

// Mock editions
export const mockEditions: Edition[] = [
  {
    id: 'edition1',
    category: 'premium',
    title: {
      gr: 'Premium Έκδοση',
      en: 'Premium Edition',
    },
    description: {
      gr: 'Πλήρης πρόσβαση σε όλες τις λειτουργίες',
      en: 'Full access to all features',
    },
    features: ['Feature 1', 'Feature 2', 'Feature 3'],
    price: '€99/month',
    icon: '⭐',
    status: 'active',
  },
]
